// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: PricingData.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

struct PricingData {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var id: String {
    get {return _id ?? String()}
    set {_id = newValue}
  }
  /// Returns true if `id` has been explicitly set.
  var hasID: Bool {return self._id != nil}
  /// Clears the value of `id`. Subsequent reads from it will return its default value.
  mutating func clearID() {self._id = nil}

  var price: Float {
    get {return _price ?? 0}
    set {_price = newValue}
  }
  /// Returns true if `price` has been explicitly set.
  var hasPrice: Bool {return self._price != nil}
  /// Clears the value of `price`. Subsequent reads from it will return its default value.
  mutating func clearPrice() {self._price = nil}

  var changePercent: Float {
    get {return _changePercent ?? 0}
    set {_changePercent = newValue}
  }
  /// Returns true if `changePercent` has been explicitly set.
  var hasChangePercent: Bool {return self._changePercent != nil}
  /// Clears the value of `changePercent`. Subsequent reads from it will return its default value.
  mutating func clearChangePercent() {self._changePercent = nil}

  var openPrice: Float {
    get {return _openPrice ?? 0}
    set {_openPrice = newValue}
  }
  /// Returns true if `openPrice` has been explicitly set.
  var hasOpenPrice: Bool {return self._openPrice != nil}
  /// Clears the value of `openPrice`. Subsequent reads from it will return its default value.
  mutating func clearOpenPrice() {self._openPrice = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _id: String? = nil
  fileprivate var _price: Float? = nil
  fileprivate var _changePercent: Float? = nil
  fileprivate var _openPrice: Float? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension PricingData: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "PricingData"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "id"),
    2: .same(proto: "price"),
    8: .same(proto: "changePercent"),
    15: .same(proto: "openPrice"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self._id) }()
      case 2: try { try decoder.decodeSingularFloatField(value: &self._price) }()
      case 8: try { try decoder.decodeSingularFloatField(value: &self._changePercent) }()
      case 15: try { try decoder.decodeSingularFloatField(value: &self._openPrice) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if let v = self._id {
      try visitor.visitSingularStringField(value: v, fieldNumber: 1)
    }
    if let v = self._price {
      try visitor.visitSingularFloatField(value: v, fieldNumber: 2)
    }
    if let v = self._changePercent {
      try visitor.visitSingularFloatField(value: v, fieldNumber: 8)
    }
    if let v = self._openPrice {
      try visitor.visitSingularFloatField(value: v, fieldNumber: 15)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: PricingData, rhs: PricingData) -> Bool {
    if lhs._id != rhs._id {return false}
    if lhs._price != rhs._price {return false}
    if lhs._changePercent != rhs._changePercent {return false}
    if lhs._openPrice != rhs._openPrice {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
